# Generated by Django 4.2.5 on 2023-10-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_student_rename_admin_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
