# Generated by Django 4.2.5 on 2023-10-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_student_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('studentname', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('occuption', models.CharField(max_length=100)),
                ('income', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('localguardianname', models.CharField(max_length=100)),
                ('localguardianaddress', models.CharField(max_length=100)),
                ('mobilenumberguardian', models.CharField(max_length=100)),
                ('mobilenumberself', models.CharField(max_length=100)),
                ('mobilenumberfather', models.CharField(max_length=100)),
                ('mobilenumbermother', models.CharField(max_length=100)),
                ('emailself', models.CharField(max_length=100)),
                ('emailparent', models.CharField(max_length=100)),
                ('accountnumber', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('accountholdername', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=100)),
                ('jeerank', models.CharField(max_length=100)),
                ('upseerank', models.CharField(max_length=100)),
                ('signatureself', models.FileField(default=None, max_length=250, upload_to='signatureself/')),
                ('signatureparent', models.FileField(default=None, max_length=250, upload_to='signatureparent/')),
                ('photo', models.FileField(default=None, max_length=250, upload_to='photo/')),
                ('roomnumber', models.CharField(max_length=100)),
                ('injuries', models.CharField(max_length=500)),
                ('allergy', models.CharField(max_length=500)),
                ('history', models.CharField(max_length=500)),
                ('declaration', models.CharField(max_length=500)),
                ('draft', models.CharField(max_length=100)),
                ('draftbankname', models.CharField(max_length=100)),
                ('favour', models.CharField(max_length=100)),
            ],
        ),
    ]
