# Generated by Django 4.2.4 on 2023-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stop_point_no', models.IntegerField()),
                ('stop_point_work', models.CharField(max_length=500)),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('turn_around_time', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
