# Generated by Django 4.2.4 on 2023-12-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_ladleinfo_delete_detail_delete_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadleUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=500)),
                ('stop_points', models.CharField(max_length=500)),
                ('stop_time', models.CharField(max_length=500)),
            ],
        ),
    ]
