# Generated by Django 5.0 on 2023-12-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_ladleupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadleUpdateRoomWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entry_time', models.CharField(max_length=500)),
                ('room', models.CharField(max_length=500)),
                ('exit_time', models.CharField(max_length=500)),
            ],
        ),
    ]
