# Generated by Django 4.2.4 on 2023-12-12 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_entriesadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='entriesadded',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 12)),
        ),
        migrations.AddField(
            model_name='ladleupdateroomwise',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 12)),
        ),
    ]
