# Generated by Django 4.2.4 on 2023-12-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_entriesadded_date_ladleupdateroomwise_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladleupdateroomwise',
            name='date',
        ),
    ]
