# Generated by Django 4.2.4 on 2023-12-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_ladleupdateroomwise_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladleupdateroomwise',
            name='stop_points',
            field=models.CharField(default='HII', max_length=500),
        ),
    ]
