# Generated by Django 4.2.4 on 2023-12-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_ladleupdateroomwise_stop_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladleupdateroomwise',
            name='stop_points',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
