# Generated by Django 4.2.4 on 2023-12-16 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_ladleupdateroomwise_stop_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladleupdateroomwise',
            name='entry_room',
            field=models.CharField(default='hii', max_length=500),
        ),
        migrations.AddField(
            model_name='ladleupdateroomwise',
            name='turn_overtime',
            field=models.CharField(default='hii', max_length=500),
        ),
        migrations.AddField(
            model_name='ladleupdateroomwise',
            name='turns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entriesadded',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 17)),
        ),
        migrations.AlterField(
            model_name='ladleupdateroomwise',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 17)),
        ),
        migrations.AlterField(
            model_name='ladleupdateroomwise',
            name='stop_points',
            field=models.CharField(default='hii', max_length=500),
        ),
    ]
