# Generated by Django 4.2.4 on 2023-12-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_ladleupdateroomwise_entry_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladleupdateroomwise',
            name='first_time',
            field=models.CharField(default='hii', max_length=500),
        ),
    ]
