# Generated by Django 4.2.4 on 2023-12-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_ladleupdateroomwise_first_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladleupdateroomwise',
            name='turn_overtime',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
