# Generated by Django 4.2.4 on 2023-12-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_ladleupdateroomwise_turn_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladleinfo',
            name='max_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ladleinfo',
            name='min_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ladleinfo',
            name='stop_point_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ladleinfo',
            name='stop_point_work',
            field=models.CharField(default='hii', max_length=500),
        ),
        migrations.AlterField(
            model_name='ladleinfo',
            name='turn_around_time',
            field=models.IntegerField(default=0),
        ),
    ]
