# Generated by Django 4.2.4 on 2023-12-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_alter_ladleinfo_max_temp_alter_ladleinfo_min_temp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LadleUpdate',
        ),
    ]
