# Generated by Django 4.2.4 on 2023-12-19 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_delete_ladleupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='entriesadded',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 19)),
        ),
        migrations.AlterField(
            model_name='ladleupdateroomwise',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 19)),
        ),
    ]
