# Generated by Django 4.2.4 on 2023-12-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ladle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('rounds_daily', models.IntegerField(default=0)),
                ('time_daily', models.TimeField()),
                ('rounds_life', models.IntegerField(default=0)),
                ('time_life', models.TimeField()),
            ],
        ),
    ]
