# Generated by Django 4.2.4 on 2023-12-19 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_remove_ladle_time_daily_remove_ladle_time_life'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(default='NO COMMENT', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='entriesadded',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 20)),
        ),
        migrations.AlterField(
            model_name='ladleupdateroomwise',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 20)),
        ),
    ]
