# Generated by Django 4.2.4 on 2023-12-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_comment_alter_entriesadded_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladle',
            name='type',
            field=models.CharField(default='hii', max_length=100),
        ),
    ]
